apiVersion: v1 
kind: Service 
metadata: 
  name: backend #note: my frontend application expects this to be exactly "backend"
  labels:
    name: backend-service 
    app: example-quiz-app
spec: 
  type: ClusterIP #groups the backend pods together
  ports: 
  - port: 5000
    targetPort: 5000
  selector: #copy the labels from the backend-deployment.yaml file into the selector below
    app: example-quiz-app 
    tier: backend 