apiVersion: apps/v1 
kind: Deployment
metadata:
  name: db-deployment 
  labels: 
    app: example-quiz-app
    tier: db
spec: 
  replicas: 1
  template: 
    metadata:
      name: db-pod
      labels:
        app: example-quiz-app 
        tier: db 
    spec: 
      containers:
      - name: db-container 
        image: nzoam93/example-app-db
        #the environmental variables required by Postgres go in this environment section
        ports: 
        - containerPort: 5432 
      volumes:
        - name: example-app-config-volume
          configMap: 
            name: db-config
  selector: 
    matchLabels:
      app: example-quiz-app