apiVersion: apps/v1 
kind: Deployment
metadata:
  name: frontend-deployment 
  labels: 
    app: example-quiz-app
    tier: frontend
spec: 
  replicas: 1
  template: 
    metadata:
      name: frontend-pod
      labels:
        app: example-quiz-app 
        tier: frontend 
    spec: 
      containers:
        - name: frontend-container 
          image: nzoam93/example-app-frontend
          ports:
          - containerPort: 80 #because nginx frontend listening on port 80
  selector: 
    matchLabels:
      app: example-quiz-app