apiVersion: v1 
kind: Service 
metadata: 
  name: frontend
  labels:
    name: frontend-service 
    app: example-quiz-app
spec: 
  #gives an external IP that is accessible on the internet
  type: LoadBalancer
  ports: 
  - port: 80 
    targetPort: 80
  selector: #copy the labels from the frontend-deployment.yaml file into the selector below
    app: example-quiz-app 
    tier: frontend 