apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce #RWX isn't allowed
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard