version: '3'
services:
  backend:
    image: nzoam93/example-app-backend:latest
    ports:
      - "5000:5000" #:5000 because we configured python to run on port 5000 in the python backend script earlier
    networks:
      - my-network
    depends_on:
      - db
    restart: on-failure
    # Specify that the backend container depends on the Postgres container
    # This ensures that the Postgres container is built and running before Python tries to access it
    
  frontend:
    image: nzoam93/example-app-frontend:latest 
    ports: 
      - "8080:80" #What you expose to the host: what the application is actually running in the container
    networks:
      - my-network

  db:
    image: nzoam93/example-app-db:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports: 
      - "5432:5432"  
    networks:
      - my-network

networks:
  my-network: